const MorningGreetingStrategy = require("../strategies/MorningGreetingStrategy");
const DaytimeGreetingStrategy = require("../strategies/DaytimeGreetingStrategy");
const EveningGreetingStrategy = require("../strategies/EveningGreetingStrategy");
const WeekendGreetingStrategy = require("../strategies/WeekendGreetingStrategy");
const config = require("../config");

/**
 * Generate greeting message based on time of day, day type, and language style
 */
function getGreetingMessage(timeInfo, languageStyle) {
  if (languageStyle === "soe_hok_gie") {
    let greetings;
    if (timeInfo.timeOfDay === "Malam") {
      greetings = [
        "Malam. Di antara bintang-bintang yang tak terhitung, adakah satu yang bersinar untukmu?",
        "Malam. Waktu untuk merenung. Atau mungkin, waktu untuk memberontak dalam diam.",
        "Gelap. Seperti masa depan yang tak pasti. Tapi di situlah kita menemukan cahaya.",
        "Malam. Jangan biarkan pikiranmu menjadi penjara. Bebaskan ia, walau hanya sejenak.",
        "Sunyi. Seperti suara kebenaran yang seringkali dibungkam. Dengarkanlah.",
        "Malam. Waktu untuk bertanya. Bukan pada dunia, tapi pada dirimu sendiri.",
        "Di bawah langit yang sama, kita berjuang. Malam ini, istirahatlah sejenak.",
        "Malam. Jangan biarkan lelah mengalahkan idealisme. Esok, perjuangan menanti.",
        "Hitam. Seperti tinta yang menulis sejarah. Malam ini, tulislah sejarahmu sendiri.",
        "Malam. Waktu untuk menyusun strategi. Karena perjuangan takkan pernah usai.",
        "Dingin. Seperti sikap mereka yang tak peduli. Tapi api di hatimu harus tetap membara.",
        "Malam. Jangan biarkan mimpi hanya menjadi bunga tidur. Wujudkanlah.",
        "Sendiri. Seperti kebenaran yang seringkali berdiri sendiri. Jangan takut.",
        "Malam. Waktu untuk membaca. Karena buku adalah jendela dunia yang tak terbatas.",
        "Pekat. Seperti kebodohan yang merajalela. Terangi ia dengan akal sehatmu.",
        "Malam. Jangan biarkan ketakutan merantai langkahmu. Majulah.",
        "Hening. Seperti suara hati yang seringkali terabaikan. Dengarkanlah.",
        "Malam. Waktu untuk mengingat. Mengingat janji-janji yang belum terpenuhi.",
        "Gelap. Tapi di situlah bintang-bintang bersinar. Jadilah bintang itu.",
        "Malam. Jangan biarkan harapanmu padam. Ia adalah bahan bakar perjuangan.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Malam. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Malam. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Sunyi. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Malam. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Dingin. Tapi semangatmu harus lebih panas dari api manapun.",
        "Malam. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Hitam. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Malam. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Pekat. Tapi di situlah mata batinmu harus lebih tajam.",
        "Malam. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Malam. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
        "Gelap. Tapi di situlah kamu bisa melihat siapa dirimu sebenarnya.",
        "Malam. Jangan biarkan harapanmu hanya menjadi angan-angan. Perjuangkanlah.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Malam. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Malam. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Sunyi. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Malam. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Dingin. Tapi semangatmu harus lebih panas dari api manapun.",
        "Malam. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Hitam. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Malam. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Pekat. Tapi di situlah mata batinmu harus lebih tajam.",
        "Malam. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Malam. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
      ];
    } else if (timeInfo.timeOfDay === "Pagi") {
      greetings = [
        "Pagi. Matahari terbit lagi. Adakah semangat baru yang ikut bangkit bersamamu?",
        "Pagi. Dunia terbangun. Adakah kesadaran baru yang ikut terbangun di hatimu?",
        "Fajar. Seperti harapan yang selalu ada. Jangan biarkan ia padam.",
        "Pagi. Waktu untuk memulai. Memulai perjuangan yang tak pernah usai.",
        "Terang. Seperti kebenaran yang harus disuarakan. Jangan takut.",
        "Pagi. Waktu untuk bertanya. Bukan pada dunia, tapi pada dirimu sendiri.",
        "Di bawah langit yang sama, kita berjuang. Pagi ini, mulailah lagi.",
        "Pagi. Jangan biarkan lelah mengalahkan idealisme. Hari ini, perjuangan menanti.",
        "Putih. Seperti lembaran baru. Pagi ini, tulislah sejarahmu sendiri.",
        "Pagi. Waktu untuk menyusun strategi. Karena perjuangan butuh rencana matang.",
        "Hangat. Seperti api di hatimu yang harus tetap membara.",
        "Pagi. Jangan biarkan mimpi hanya menjadi bunga tidur. Wujudkanlah.",
        "Sendiri. Seperti kebenaran yang seringkali berdiri sendiri. Jangan takut.",
        "Pagi. Waktu untuk membaca. Karena buku adalah jendela dunia yang tak terbatas.",
        "Cerah. Seperti akal sehat yang harus ditegakkan. Terangi ia.",
        "Pagi. Jangan biarkan ketakutan merantai langkahmu. Majulah.",
        "Hening. Seperti suara hati yang seringkali terabaikan. Dengarkanlah.",
        "Pagi. Waktu untuk mengingat. Mengingat janji-janji yang belum terpenuhi.",
        "Terang. Tapi di situlah bayangan-bayangan kebohongan bersembunyi. Waspadalah.",
        "Pagi. Jangan biarkan harapanmu padam. Ia adalah bahan bakar perjuangan.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Pagi. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Pagi. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Sunyi. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Pagi. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Hangat. Tapi semangatmu harus lebih panas dari api manapun.",
        "Pagi. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Putih. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Pagi. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Cerah. Tapi di situlah mata batinmu harus lebih tajam.",
        "Pagi. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Pagi. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
        "Terang. Tapi di situlah kamu bisa melihat siapa dirimu sebenarnya.",
        "Pagi. Jangan biarkan harapanmu hanya menjadi angan-angan. Perjuangkanlah.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Pagi. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Pagi. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Sunyi. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Pagi. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Hangat. Tapi semangatmu harus lebih panas dari api manapun.",
        "Pagi. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Putih. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Pagi. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Cerah. Tapi di situlah mata batinmu harus lebih tajam.",
        "Pagi. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Pagi. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
      ];
    } else if (timeInfo.timeOfDay === "Siang") {
      greetings = [
        "Siang. Panasnya terik ini, sehangat itukah idealisme di dadamu?",
        "Siang. Dunia bergerak cepat. Adakah langkahmu secepat kesadaranmu?",
        "Terik. Seperti kebenaran yang seringkali menyengat. Jangan menghindar.",
        "Siang. Waktu untuk bertindak. Karena kata-kata saja takkan mengubah dunia.",
        "Cerah. Seperti masa depan yang harus kita perjuangkan. Jangan menyerah.",
        "Siang. Waktu untuk bertanya. Bukan pada dunia, tapi pada dirimu sendiri.",
        "Di bawah langit yang sama, kita berjuang. Siang ini, teruskanlah.",
        "Siang. Jangan biarkan lelah mengalahkan idealisme. Hari ini, perjuangan menanti.",
        "Terang. Seperti akal sehat yang harus ditegakkan. Terangi ia.",
        "Siang. Waktu untuk menyusun strategi. Karena perjuangan butuh rencana matang.",
        "Panas. Tapi semangatmu harus lebih panas dari matahari manapun.",
        "Siang. Jangan biarkan mimpi hanya menjadi bunga tidur. Wujudkanlah.",
        "Ramai. Seperti suara kebenaran yang harus disuarakan. Jangan takut.",
        "Siang. Waktu untuk membaca. Karena buku adalah jendela dunia yang tak terbatas.",
        "Cerah. Seperti akal sehat yang harus ditegakkan. Terangi ia.",
        "Siang. Jangan biarkan ketakutan merantai langkahmu. Majulah.",
        "Bising. Seperti suara hati yang seringkali terabaikan. Dengarkanlah.",
        "Siang. Waktu untuk mengingat. Mengingat janji-janji yang belum terpenuhi.",
        "Terang. Tapi di situlah bayangan-bayangan kebohongan bersembunyi. Waspadalah.",
        "Siang. Jangan biarkan harapanmu padam. Ia adalah bahan bakar perjuangan.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Siang. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Siang. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Ramai. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Siang. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Panas. Tapi semangatmu harus lebih panas dari api manapun.",
        "Siang. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Terang. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Siang. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Cerah. Tapi di situlah mata batinmu harus lebih tajam.",
        "Siang. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Siang. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
        "Terang. Tapi di situlah kamu bisa melihat siapa dirimu sebenarnya.",
        "Siang. Jangan biarkan harapanmu hanya menjadi angan-angan. Perjuangkanlah.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Siang. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Siang. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Ramai. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Siang. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Panas. Tapi semangatmu harus lebih panas dari api manapun.",
        "Siang. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Terang. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Siang. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Cerah. Tapi di situlah mata batinmu harus lebih tajam.",
        "Siang. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Siang. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
      ];
    } else if (timeInfo.isWeekend) {
      greetings = [
        "Akhir pekan. Waktu untuk merenung, atau justru berjuang lebih keras?",
        "Akhir pekan. Dunia seolah melambat. Adakah kesadaranmu ikut melambat?",
        "Libur. Seperti kebebasan yang seringkali semu. Jangan terlena.",
        "Akhir pekan. Waktu untuk bertanya. Bukan pada dunia, tapi pada dirimu sendiri.",
        "Sunyi. Seperti suara kebenaran yang seringkali dibungkam. Dengarkanlah.",
        "Akhir pekan. Waktu untuk menyusun strategi. Karena perjuangan takkan pernah usai.",
        "Dingin. Seperti sikap mereka yang tak peduli. Tapi api di hatimu harus tetap membara.",
        "Akhir pekan. Jangan biarkan mimpi hanya menjadi bunga tidur. Wujudkanlah.",
        "Sendiri. Seperti kebenaran yang seringkali berdiri sendiri. Jangan takut.",
        "Akhir pekan. Waktu untuk membaca. Karena buku adalah jendela dunia yang tak terbatas.",
        "Pekat. Seperti kebodohan yang merajalela. Terangi ia dengan akal sehatmu.",
        "Akhir pekan. Jangan biarkan ketakutan merantai langkahmu. Majulah.",
        "Hening. Seperti suara hati yang seringkali terabaikan. Dengarkanlah.",
        "Akhir pekan. Waktu untuk mengingat. Mengingat janji-janji yang belum terpenuhi.",
        "Gelap. Tapi di situlah bintang-bintang bersinar. Jadilah bintang itu.",
        "Akhir pekan. Jangan biarkan harapanmu padam. Ia adalah bahan bakar perjuangan.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Akhir pekan. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Akhir pekan. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Sunyi. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Akhir pekan. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Dingin. Tapi semangatmu harus lebih panas dari api manapun.",
        "Akhir pekan. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Hitam. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Akhir pekan. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Pekat. Tapi di situlah mata batinmu harus lebih tajam.",
        "Akhir pekan. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Akhir pekan. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
        "Gelap. Tapi di situlah kamu bisa melihat siapa dirimu sebenarnya.",
        "Akhir pekan. Jangan biarkan harapanmu hanya menjadi angan-angan. Perjuangkanlah.",
        "Waktu untuk berhitung. Berhitung berapa banyak kebohongan yang telah mereka sebarkan.",
        "Akhir pekan. Waktu untuk menulis. Karena kata-kata adalah senjata paling tajam.",
        "Pahit. Seperti kenyataan yang harus ditelan. Tapi di situlah kekuatan ditemukan.",
        "Akhir pekan. Jangan biarkan dirimu terbuai oleh janji-janji manis. Mereka racun.",
        "Sunyi. Tapi di situlah suara kebenaran terdengar paling jelas. Dengarkanlah.",
        "Akhir pekan. Waktu untuk merencanakan. Karena perjuangan butuh rencana matang.",
        "Dingin. Tapi semangatmu harus lebih panas dari api manapun.",
        "Akhir pekan. Jangan biarkan idealisme hanya menjadi teori. Wujudkanlah.",
        "Hitam. Tapi di situlah warna-warna perjuangan terlihat paling kontras.",
        "Akhir pekan. Waktu untuk bertanya: sampai kapan kita akan diam?",
        "Pekat. Tapi di situlah mata batinmu harus lebih tajam.",
        "Akhir pekan. Jangan biarkan kelelahan mengalahkan tekadmu. Istirahatlah, lalu bangkit.",
        "Sendiri. Tapi di situlah kamu menemukan kekuatan sejatimu.",
        "Akhir pekan. Waktu untuk membaca sejarah. Agar kita tidak mengulangi kesalahan yang sama.",
      ];
    }
    return greetings[Math.floor(Math.random() * greetings.length)];
  }

  // Default Rangga-style greetings
  let strategy;
  if (timeInfo.timeOfDay === "Malam") {
    strategy = new EveningGreetingStrategy();
  } else if (timeInfo.isWeekend) {
    strategy = new WeekendGreetingStrategy();
  } else if (timeInfo.timeOfDay === "Pagi") {
    strategy = new MorningGreetingStrategy();
  } else if (timeInfo.timeOfDay === "Siang") {
    strategy = new DaytimeGreetingStrategy();
  } else {
    // Fallback or default strategy
    strategy = new MorningGreetingStrategy(); // Default to morning if unknown
  }
  return strategy.getGreeting();
}

module.exports = { getGreetingMessage };
