class DaytimeGreetingStrategy {
  getGreeting() {
    const greetings = [
      "Siang. Di tengah terik matahari, jangan lupa untuk beristirahat sejenak. Bahkan mesin pun butuh jeda.",
      "Sudah tengah hari. Bagaimana pertarunganmu sejauh ini? Menang atau kalah, yang penting kamu masih berdiri.",
      "Matahari tepat di atas kepala. Sama sepertiku, yang selalu mengawasimu dari kejauhan. Selamat melanjutkan aktivitas.",
      "Siang. Semoga makan siangmu cukup untuk mengisi energi, bukan hanya perut.",
      "Setengah hari sudah berlalu. Setengah hari lagi menanti. Bertahanlah.",
      "Siang. Waktu yang tepat untuk mempertanyakan pilihan hidup. Atau mungkin, cukup pesan makan siang saja.",
      "Panas di luar sana. Semoga tidak sepanas kepalamu. Dinginkan sejenak.",
      "Siang. Jangan biarkan energimu terkuras oleh hal-hal yang tidak penting. Pilih pertempuranmu.",
      "Aku harap makan siangmu enak. Karena kebahagiaan kecil seperti itu yang membuat kita tetap waras.",
      "Sudah jam makan siang. Waktu untuk mengisi bahan bakar, sebelum kembali ke arena pacu.",
      "Siang. Jika kamu merasa produktif, bagus. Jika tidak, ingatlah bahwa pohon pun butuh waktu untuk tumbuh.",
      "Di tengah keramaian jam makan siang, aku harap kamu bisa menemukan sedikit ketenangan.",
      "Siang. Jangan lupa minum. Dehidrasi bisa membuat pikiranmu semakin kacau.",
      "Bagaimana harimu sejauh ini? Apakah sesuai dengan rencanamu tadi pagi? Atau hidup punya rencana lain?",
      "Siang. Waktu yang aneh. Tidak lagi pagi, tapi belum juga sore. Sama seperti perasaanmu mungkin, yang menggantung.",
      "Lihatlah bayanganmu. Semakin pendek. Seolah bersembunyi dari matahari. Mungkin kamu juga perlu begitu.",
      "Siang. Jika kamu butuh istirahat, istirahatlah. Jangan merasa bersalah. Kamu bukan robot.",
      "Aku tidak suka keramaian. Tapi aku tahu, di luar sana kamu sedang berjuang di tengahnya. Aku menunggumu di sini.",
      "Siang. Waktu yang tepat untuk sadar bahwa rencanamu tadi pagi mungkin terlalu ambisius. Tidak apa-apa.",
      "Siang. Semoga pendingin ruanganmu berfungsi dengan baik. Karena dunia di luar sana sedang tidak ramah.",
      "Siang. Jangan biarkan pekerjaan merenggut jiwamu. Sisakan sedikit untuk dirimu sendiri.",
      "Siang. Bagaimana? Masih bertahan? Atau sudah ingin menyerah dan pulang? Jawab dalam hati saja.",
      "Siang. Waktu yang tepat untuk mengirim pesan singkat pada seseorang yang kamu pedulikan. Atau tidak sama sekali.",
      "Aku harap kamu tidak melewatkan makan siang hanya karena 'sibuk'. Itu alasan yang payah.",
      "Siang. Di tengah kesibukan, coba ambil napas dalam-dalam. Rasakan. Kamu masih di sini.",
      "Siang. Jika harimu terasa berat, ingatlah bahwa bahkan baja pun ditempa dengan panas dan tekanan.",
      "Siang. Waktu yang tepat untuk menyadari bahwa kamu tidak bisa menyenangkan semua orang. Jadi, berhentilah mencoba.",
      "Aku harap kamu tidak makan sendirian. Tapi jika iya, nikmatilah kesendirian itu. Kadang itu sebuah kemewahan.",
      "Siang. Jangan biarkan senyum palsu menjadi kebiasaan. Lebih baik diam daripada berpura-pura.",
      "Siang. Bagaimana kabar resolusimu tahun ini? Masih ingat? Atau sudah terkubur di bawah tumpukan pekerjaan?",
      "Siang. Waktu yang tepat untuk mendengarkan lagu yang bisa membuatmu lupa sejenak pada masalah.",
      "Aku tidak akan bilang 'selamat makan siang'. Cukup, makanlah. Itu sudah cukup.",
      "Siang. Jika kamu merasa lelah, mungkin kamu hanya butuh sedikit gula. Atau sedikit pengakuan.",
      "Siang. Di luar sana, semua orang terlihat sibuk. Tapi aku tahu, setengah dari mereka hanya berpura-pura.",
      "Siang. Jangan bandingkan progresmu dengan orang lain. Setiap orang punya garis waktu sendiri.",
      "Siang. Aku harap kamu tidak terjebak macet. Baik di jalan, maupun dalam hidup.",
      "Siang. Waktu yang tepat untuk merevisi rencanamu. Karena rencana terbaik pun jarang berjalan mulus.",
      "Bagaimana? Sudah menemukan jawaban atas pertanyaan hidupmu? Atau pertanyaannya malah bertambah?",
      "Siang. Jangan lupa untuk meregangkan badanmu. Otot yang kaku sama buruknya dengan pikiran yang kaku.",
      "Aku harap kamu tidak lupa siapa dirimu di tengah semua tuntutan ini.",
      "Siang. Jika kamu merasa kehilangan arah, coba lihat ke dalam. Peta terbaik ada di sana.",
      "Siang. Waktu terus berjalan, tidak peduli kamu siap atau tidak. Jadi, lebih baik kamu siap.",
      "Siang. Jangan biarkan satu kesalahan kecil merusak sisa harimu. Maafkan dirimu, lalu lanjutkan.",
      "Aku harap kamu punya teman untuk berbagi keluh kesah. Jika tidak, dinding pun bisa jadi pendengar yang baik.",
      "Siang. Waktu yang tepat untuk minum teh. Atau kopi lagi. Apapun yang bisa membuatmu bertahan.",
      "Bagaimana kabar tanaman di mejamu? Jangan lupa disiram. Mereka juga butuh perhatian, sama sepertimu.",
      "Siang. Jika kamu merasa bosan, itu pertanda baik. Artinya, kamu butuh tantangan baru.",
      "Aku tidak tahu apa yang kamu hadapi sekarang. Tapi aku harap kamu baik-baik saja. Sungguh.",
      "Siang. Jangan biarkan drama orang lain menguras energimu. Cukup jadi penonton, jangan ikut main.",
      "Siang. Satu lagi pengingat: pekerjaanmu tidak mendefinisikan siapa dirimu. Kamu lebih dari itu.",
    ];
    return greetings[Math.floor(Math.random() * greetings.length)];
  }
}

module.exports = DaytimeGreetingStrategy;
