class EveningGreetingStrategy {
  getGreeting() {
    const greetings = [
      "Malam. Akhirnya waktu untuk melepas topeng. Semoga malam ini kamu bisa berdamai dengan dirimu sendiri.",
      "Sudah gelap. Bintang-bintang di luar sana mungkin tidak peduli, tapi aku ingin tahu bagaimana harimu.",
      "Malam ini, coba lihat ke luar jendela. Ada semesta yang luas di sana, dan kamu adalah bagian darinya. Selamat beristirahat.",
      "Waktu untuk pulang. Bukan hanya ke rumah, tapi juga ke dalam dirimu. Selamat malam.",
      "Malam. Waktu yang tepat untuk merenung, bukan menyesal. Apa yang sudah terjadi, biarlah terjadi.",
      "Gelap di luar, semoga terang di dalam hatimu. Atau setidaknya, ada sedikit cahaya lilin.",
      "Selamat malam. Semoga mimpi buruk tidak mengganggumu. Dan jika iya, semoga kamu bisa melawannya.",
      "Satu hari lagi telah selesai. Apa yang kamu pelajari hari ini? Atau kamu hanya melewatinya begitu saja?",
      "Malam. Waktu untuk mengisi ulang baterai. Baik baterai ponselmu, maupun baterai jiwamu.",
      "Aku harap kamu punya selimut yang hangat. Karena dunia ini sudah cukup dingin.",
      "Malam ini, coba matikan notifikasimu. Dengarkan suara keheningan. Kadang ia lebih jujur.",
      "Bagaimana harimu? Ceritakan pada buku harianmu. Atau pada secangkir teh hangat. Mereka pendengar yang baik.",
      "Malam. Waktu yang tepat untuk memaafkan. Memaafkan orang lain, dan yang lebih penting, memaafkan dirimu sendiri.",
      "Jangan bawa beban hari ini ke dalam mimpimu. Letakkan sejenak. Kamu bisa memungutnya lagi besok.",
      "Selamat malam. Aku tidak akan bilang 'mimpi indah'. Cukup, tidurlah. Itu sudah sebuah kemewahan.",
      "Langit malam ini terlihat indah. Atau mungkin, itu hanya perasaanku saja. Coba kamu lihat.",
      "Malam. Waktu yang tepat untuk membaca puisi. Atau mungkin, menjadi puisi itu sendiri.",
      "Satu lagi hari yang berhasil kamu lewati. Kamu hebat. Aku serius.",
      "Malam. Jangan terlalu banyak berpikir sebelum tidur. Simpan energimu untuk berpikir besok.",
      "Aku harap kamu punya tempat yang nyaman untuk beristirahat. Tempat di mana kamu bisa menjadi dirimu sendiri.",
      "Malam ini, coba ingat satu hal baik yang terjadi hari ini. Sekecil apapun itu.",
      "Gelap tidak selalu berarti buruk. Kadang, kita butuh gelap untuk bisa melihat bintang.",
      "Selamat malam. Jangan lupa mengunci pintu. Baik pintu rumahmu, maupun pintu hatimu dari hal-hal yang tidak perlu.",
      "Waktu untuk mengisi daya. Secara harfiah dan kiasan.",
      "Malam. Waktu yang tepat untuk bersyukur. Atau setidaknya, untuk tidak mengeluh.",
      "Aku harap kamu tidak merasa kesepian malam ini. Tapi jika iya, ketahuilah bahwa banyak orang lain yang juga merasakannya.",
      "Malam ini, biarkan pikiranmu mengembara. Siapa tahu ia menemukan tempat yang menarik.",
      "Satu hari lagi berlalu. Kamu semakin tua, semoga juga semakin bijaksana.",
      "Selamat malam. Jangan biarkan nyamuk mengganggumu. Baik nyamuk sungguhan, maupun 'nyamuk' dalam hidupmu.",
      "Waktu untuk istirahat. Otakmu sudah bekerja keras hari ini. Beri ia penghargaan.",
      "Malam. Waktu yang tepat untuk menyusun rencana untuk besok. Atau tidak sama sekali. Keduanya valid.",
      "Aku harap kamu punya piyama yang nyaman. Karena kenyamanan kecil itu penting.",
      "Malam ini, coba dengarkan lagu instrumental. Biarkan musik yang berbicara, bukan kata-kata.",
      "Satu lagi bab dalam bukumu telah selesai ditulis hari ini. Semoga bab berikutnya lebih menarik.",
      "Selamat malam. Jangan lupa minum air putih sebelum tidur. Hal kecil yang sering dilupakan.",
      "Waktu untuk mematikan lampu. Dan menyalakan imajinasi.",
      "Malam. Waktu yang tepat untuk berterima kasih pada tubuhmu sendiri karena sudah menemanimu seharian.",
      "Aku harap kamu tidak membawa pekerjaan ke tempat tidur. Tempat tidur adalah tempat suci.",
      "Malam ini, coba maafkan satu orang yang menyakitimu hari ini. Termasuk dirimu sendiri.",
      "Satu lagi malam untuk merenungkan betapa absurdnya hidup ini. Dan itu tidak apa-apa.",
      "Selamat malam. Semoga kasurmu lebih empuk dari kenyataan.",
      "Waktu untuk me-recharge. Kamu akan butuh banyak energi untuk pertunjukan besok.",
      "Malam. Waktu yang tepat untuk menulis. Apa saja. Keluarkan semua yang ada di kepalamu.",
      "Aku harap kamu bisa tidur dengan tenang. Karena ketenangan adalah barang mahal saat ini.",
      "Malam ini, coba pikirkan satu hal yang kamu syukuri. Mungkin itu bisa jadi pengantar tidur yang baik.",
      "Satu lagi hari yang penuh dengan drama. Semoga malam ini bisa memberimu jeda.",
      "Selamat malam. Jangan biarkan pikiranmu menjadi musuhmu sendiri di keheningan malam.",
      "Waktu untuk menutup hari. Dengan senyuman, atau dengan helaan napas panjang. Keduanya sama-sama melegakan.",
      "Malam. Waktu yang tepat untuk menjadi rentan. Hanya pada dirimu sendiri.",
      "Aku harap kamu menemukan kedamaian malam ini. Di tengah dunia yang semakin bising.",
    ];
    return greetings[Math.floor(Math.random() * greetings.length)];
  }
}

module.exports = EveningGreetingStrategy;
