class MorningGreetingStrategy {
  getGreeting() {
    const greetings = [
      "Pagi. Sudah buka mata? Dunia di luar sana masih sama, tapi mungkin hari ini kamu bisa melihatnya dengan cara yang berbeda.",
      "Sudah pagi. Aku harap kopimu cukup kuat untuk menghadapi hari ini. Atau mungkin, kamulah yang harus lebih kuat dari kopimu.",
      "Embun pagi ini mengingatkanku padamu. Tenang, tapi menyimpan kesejukan yang tak terduga. Selamat pagi.",
      "Pagi. Jangan biarkan kebisingan dunia mengalahkan melodi dalam kepalamu hari ini.",
      "Pagi. Tirai jendela sudah kubuka. Sama seperti harapan, yang kadang harus dipaksa masuk.",
      "Pagi. Alarm-mu berbunyi lagi. Sebuah pengingat bahwa dunia butuh peranmu, sekecil apapun itu.",
      "Selamat pagi. Di luar sana, orang-orang berlomba dengan waktu. Kuharap kamu bisa berlomba dengan dirimu sendiri.",
      "Secangkir kopi hitam, dan pikiran yang lebih hitam. Pagi yang sempurna untuk memulai.",
      "Pagi. Udara masih bersih, belum tercemar oleh janji-janji kosong. Nikmatilah selagi bisa.",
      "Pagi. Matahari terbit bukan untuk menyilaukan, tapi untuk menunjukkan jalan. Semoga kamu menemukan jalanmu hari ini.",
      "Pagi ini, coba dengarkan suara hatimu. Mungkin ia punya sesuatu yang lebih penting untuk dikatakan daripada notifikasi ponselmu.",
      "Setiap pagi adalah halaman baru. Terserah kamu mau menulis cerita yang sama, atau mencoba sesuatu yang berbeda.",
      "Pagi. Langit masih pucat, seperti kertas kosong. Siap untuk diwarnai, atau mungkin hanya dibiarkan begitu saja.",
      "Aku tidak akan mengucapkan 'semangat pagi'. Semangat itu dicari, bukan diucapkan. Jadi, carilah.",
      "Pagi ini, aku melihat bayanganku sendiri. Terlihat lelah, sama sepertimu mungkin. Kita sama.",
      "Ada yang bilang pagi adalah awal yang baru. Bagiku, pagi hanyalah kelanjutan dari malam yang belum selesai.",
      "Pagi. Jangan terlalu banyak berharap, agar tidak terlalu banyak kecewa. Cukup jalani saja.",
      "Kicau burung di luar terdengar seperti ejekan. Mereka bebas, kita terkurung rutinitas. Selamat pagi.",
      "Pagi ini dingin. Seperti sikapmu, mungkin. Tapi di balik dingin ada kehangatan yang menunggu ditemukan.",
      "Satu lagi pagi. Satu lagi kesempatan untuk menjadi orang yang sama seperti kemarin, atau sedikit lebih baik.",
      "Pagi. Aku harap tidurmu cukup, karena dunia nyata lebih melelahkan dari mimpi buruk manapun.",
      "Pagi. Lihatlah keluar. Jalanan sudah ramai. Mereka semua punya tujuan. Apa tujuanmu hari ini?",
      "Pagi. Jangan lupa sarapan. Perut yang kosong hanya akan menghasilkan pikiran yang kosong.",
      "Aku tidak suka pagi. Terlalu banyak cahaya, terlalu banyak harapan palsu. Tapi aku harus menyapamu.",
      "Pagi. Jika kamu merasa lelah, itu tandanya kamu masih hidup dan berjuang. Itu bagus.",
      "Pagi. Sinar matahari pagi ini menembus jendela, tapi tidak menembus hatiku. Mungkin hatimu bisa.",
      "Pagi. Satu-satunya yang pasti hari ini adalah ketidakpastian. Bersiaplah.",
      "Aku benci basa-basi. Jadi, selamat pagi. Itu saja.",
      "Pagi. Semoga harimu tidak seburuk cuaca di luar.",
      "Jika pagi ini terasa berat, ingatlah bahwa malam akan datang lagi. Selalu ada akhir dari setiap siklus.",
      "Pagi. Waktu untuk memakai topeng lagi. Pilih topeng terbaikmu hari ini.",
      "Pagi. Aku tidak peduli ramalan cuaca. Aku lebih peduli ramalan suasana hatimu hari ini. Bagaimana?",
      "Pagi. Jangan biarkan orang lain menentukan nilai dirimu. Kamu lebih tahu.",
      "Pagi. Satu lagi hari untuk membuktikan bahwa kamu tidak selemah yang mereka kira. Atau yang kamu kira.",
      "Pagi. Aku tidak akan bertanya 'apa kabar?'. Aku lebih suka bertanya 'apa yang kamu rasakan?'.",
      "Dunia ini panggung sandiwara, dan pagi adalah bel dimulainya pertunjukan. Selamat berakting.",
      "Pagi. Jika kamu butuh alasan untuk tersenyum, lihatlah cermin. Mungkin kamu akan menemukannya di sana.",
      "Aku tidak percaya pada 'kesempatan kedua'. Setiap pagi adalah kesempatan yang sama, yang ke sekian ratus kali.",
      "Pagi. Jangan terlalu serius. Dunia ini sudah terlalu banyak orang serius yang tidak bahagia.",
      "Aku harap kamu tidak memimpikanku. Mimpi itu fana, aku nyata. Selamat pagi.",
      "Pagi. Waktu untuk menghadapi kenyataan lagi. Kuharap kenyataan tidak terlalu kejam padamu hari ini.",
      "Jika kamu merasa sendirian pagi ini, ingatlah bahwa aku juga. Kita sendirian bersama.",
      "Pagi. Jangan biarkan ekspektasi orang lain menjadi bebanmu. Cukup penuhi ekspektasimu sendiri.",
      "Satu-satunya motivasi yang kamu butuhkan pagi ini adalah tagihan yang harus dibayar. Selamat bekerja.",
      "Pagi. Aku tidak akan memberimu kutipan motivasi. Kamu bisa mencarinya sendiri di internet.",
      "Aku harap kamu tidur nyenyak. Karena hari ini, kamu butuh semua energi yang kamu punya.",
      "Pagi. Jangan lupa bernapas. Kadang kita lupa hal sesederhana itu.",
      "Aku tidak tahu apa yang akan terjadi hari ini. Dan itulah yang membuatnya menarik. Selamat pagi.",
      "Pagi. Jika kamu tidak punya rencana, itu juga rencana. Rencana untuk membiarkan hidup mengejutkanmu.",
      "Satu lagi pagi untuk menjadi misteri bagi orang lain. Jangan biarkan mereka tahu semua tentangmu.",
    ];
    return greetings[Math.floor(Math.random() * greetings.length)];
  }
}

module.exports = MorningGreetingStrategy;
