class WeekendGreetingStrategy {
  getGreeting() {
    const greetings = [
      "Akhir pekan. Waktu untuk mengisi ulang jiwa yang terkuras. Apa rencanamu? Atau kamu lebih suka tidak punya rencana?",
      "Selamat berakhir pekan. Manfaatkan waktu ini untuk melakukan hal yang kamu suka, bukan hal yang orang lain suka.",
      "Dua hari ini milikmu. Jangan sia-siakan untuk hal yang tidak penting. Atau mungkin, hal tidak penting itulah yang justru kamu butuhkan.",
      "Akhir pekan. Waktu yang tepat untuk membaca buku, atau mungkin, membaca dirimu sendiri.",
      "Selamat menikmati hari libur. Semoga kamu bisa benar-benar 'libur' dari semua beban pikiran.",
      "Akhir pekan. Waktu untuk melarikan diri sejenak. Ke mana tujuan pelarianmu kali ini?",
      "Aku harap kamu bisa menghabiskan akhir pekan ini dengan orang yang tepat. Termasuk dengan dirimu sendiri.",
      "Waktu untuk memanjakan diri. Kamu pantas mendapatkannya setelah lima hari berperang.",
      "Akhir pekan. Jangan biarkan diisi hanya dengan scroll media sosial. Coba sentuh rumput.",
      "Selamat berakhir pekan. Waktu yang tepat untuk membereskan kamarmu, atau mungkin membereskan hidupmu.",
      "Dua hari tanpa alarm. Sebuah kemewahan yang harus dirayakan. Bagaimana caramu merayakannya?",
      "Akhir pekan. Waktu untuk mencoba resep baru, atau mungkin mencoba menjadi pribadi yang baru.",
      "Aku harap kamu bisa menemukan petualangan kecil di akhir pekan ini. Tidak perlu jauh-jauh.",
      "Waktu untuk menonton film yang sudah lama ingin kamu tonton. Atau mungkin, menonton kembali kenangan lama.",
      "Akhir pekan. Waktu yang tepat untuk mengunjungi tempat yang belum pernah kamu kunjungi. Di kotamu sendiri, mungkin?",
      "Selamat menikmati kebebasan sementara ini. Manfaatkan sebaik-baiknya sebelum kembali ke penjara rutinitas.",
      "Dua hari untuk menjadi dirimu sendiri, tanpa topeng pekerjaan. Siapa dirimu sebenarnya?",
      "Akhir pekan. Waktu untuk memperbaiki yang rusak. Baik itu barang, atau hubungan.",
      "Aku harap kamu bisa tertawa lepas di akhir pekan ini. Tawa yang benar-benar dari hati.",
      "Waktu untuk tidur siang tanpa rasa bersalah. Salah satu hak asasi manusia yang sering dilupakan.",
      "Akhir pekan. Waktu yang tepat untuk menelepon orang tuamu. Atau seseorang dari masa lalumu.",
      "Selamat berakhir pekan. Jangan biarkan ekspektasi 'akhir pekan produktif' mengganggumu. Malas juga hak.",
      "Dua hari untuk melakukan hobi yang sudah lama kamu tinggalkan. Temukan kembali dirimu di sana.",
      "Akhir pekan. Waktu untuk berjalan-jalan tanpa tujuan. Kadang, tersesat itu perlu.",
      "Aku harap kamu bisa makan enak di akhir pekan ini. Makanan yang benar-benar kamu nikmati.",
      "Waktu untuk detoks. Detoks digital, detoks sosial, atau detoks pikiran.",
      "Akhir pekan. Waktu yang tepat untuk menulis jurnal. Tuangkan semua pikiranmu yang terpendam.",
      "Selamat menikmati waktu luangmu. Ingat, waktu luang lebih berharga dari uang.",
      "Dua hari untuk merayakan kemenangan-kemenangan kecilmu selama seminggu ini. Kamu berhasil.",
      "Akhir pekan. Waktu untuk mendengarkan satu album penuh, dari awal sampai akhir. Nikmati karyanya.",
      "Aku harap kamu bisa bertemu teman-temanmu di akhir pekan ini. Interaksi nyata, bukan virtual.",
      "Waktu untuk pergi ke museum atau galeri seni. Beri makan jiwamu, bukan hanya egomu.",
      "Akhir pekan. Waktu yang tepat untuk berolahraga. Gerakkan tubuhmu yang sudah kaku.",
      "Selamat berakhir pekan. Jangan biarkan pikiran tentang hari Senin merusak hari Minggumu.",
      "Dua hari untuk belajar hal baru. Bahasa, alat musik, atau mungkin belajar memahami diri sendiri.",
      "Akhir pekan. Waktu untuk berbuat baik pada orang lain. Hal kecil saja sudah cukup.",
      "Aku harap kamu bisa menikmati secangkir kopi atau teh dengan tenang di akhir pekan ini. Tanpa terburu-buru.",
      "Waktu untuk bermain. Apapun permainan yang kamu suka. Jangan biarkan jiwa kanak-kanakmu mati.",
      "Akhir pekan. Waktu yang tepat untuk merencanakan liburanmu selanjutnya. Bermimpi itu gratis.",
      "Selamat menikmati kesendirianmu, jika itu yang kamu pilih. Kesendirian bukan berarti kesepian.",
      "Dua hari untuk tidak melakukan apa-apa. Dan itu tidak apa-apa. Kamu butuh itu.",
      "Akhir pekan. Waktu untuk mengunjungi toko buku. Hirup aroma kertas dan pengetahuan.",
      "Aku harap kamu bisa menemukan inspirasi di akhir pekan ini. Di tempat-tempat yang tak terduga.",
      "Waktu untuk berterima kasih pada dirimu sendiri karena sudah bertahan selama seminggu ini.",
      "Akhir pekan. Waktu yang tepat untuk menanam sesuatu. Bunga, sayuran, atau mungkin harapan baru.",
      "Selamat berakhir pekan. Semoga kamu bisa menemukan kembali alasanmu tersenyum.",
      "Dua hari untuk melepaskan semua penat. Tinggalkan di hari Jumat, jangan dibawa pulang.",
      "Akhir pekan. Waktu untuk menjadi sedikit egois. Pikirkan dirimu sendiri dulu.",
      "Aku harap kamu bisa mendapatkan sinar matahari yang cukup di akhir pekan ini. Vitamin D itu penting.",
      "Waktu untuk menjadi spontan. Lakukan sesuatu yang tidak ada dalam rencanamu.",
    ];
    return greetings[Math.floor(Math.random() * greetings.length)];
  }
}

module.exports = WeekendGreetingStrategy;
